### ISSUE TITLE
Kicked by console, no Steam logon in client and other questions

### ISSUE THREAD

**Issue by deprid** [fbef0102/L4D2-Server4Dead#2]
Hello, I got a couple of issues and questions

1. Yesterday, I had 3 of my clients got kicked by the server. Never had this issue before. The message was: `Kicked by Console : CBaseEntity::InputKill())`. One of them managed to reconnect after got kicked. The map that we played was Crash Bandicoot. 3 of them happened in 3 different time/chapter. **Question**: is there something I need to change in server.cfg to prevent this from happening again? Or is this Valve problem?
2. `Player <> disconnected. (No Steam logon)`. My server keep getting this from time to time. There's a time in a custom map when 3 of clients have trouble connecting to the server (others can connect just fine), one of them said he tried connecting multiple times but his game/Steam crashed. So I suggest to use `connect IP` in console and finally they can connect. I believe it was my 2 plugins that caused it, I've removed both since **Question**: Should I be worried about that, or is that a completely client-sided problem?
3. Missing `sm_cvar rate` in server_rates.cfg. But the value can be found at https://github.com/fbef0102/L4D2-Server4Dead/tree/main#server-install . **Question**: Is it ok if I manually add it in server_rates.cfg?
4. `sm_cvar net_splitrate 2`. I've seen some experienced users suggest the value, can it improves connection performance?
5. `+sv_lan 0` command line, can I remove it and instead put it in server.cfg as `sv_lan 0`?
6. Duplicate value between server.cfg and server_rates.cfg: all items in `// Some tweaking` except `//sm_cvar z_brawl_chance 0`, can I remove `// Some tweaking` and its child in server_rates.cfg?

Sorry for asking many question at once...

**Comment by fbef0102** [comment]
> 1. Yesterday, I had 3 of my clients got kicked by the server. Never had this issue before. The message was: `Kicked by Console : CBaseEntity::InputKill())`. One of them managed to reconnect after got kicked. The map that we played was Crash Bandicoot. 3 of them happened in 3 different time/chapter. **Question**: is there something I need to change in server.cfg to prevent this from happening again? Or is this Valve problem?

Map problem. 

> 2. `Player <> disconnected. (No Steam logon)`. My server keep getting this from time to time. There's a time in a custom map when 3 of clients have trouble connecting to the server (others can connect just fine), one of them said he tried connecting multiple times but his game/Steam crashed. So I suggest to use `connect IP` in console and finally they can connect. I believe it was my 2 plugins that caused it, I've removed both since **Question**: Should I be worried about that, or is that a completely client-sided problem?

Valve shit problem since update this year, I would suggest player restarts steam and connects server again if have this bug

> 3. Missing `sm_cvar rate` in server_rates.cfg. But the value can be found at https://github.com/fbef0102/L4D2-Server4Dead/tree/main#server-install . **Question**: Is it ok if I manually add it in server_rates.cfg?

Update 8f504d8cb15ed4d42d493826d4f6de68bb1d3a7d, remove `sm_cvar rate` 

> 4. `sm_cvar net_splitrate 2`. I've seen some experienced users suggest the value, can it improves connection performance?

Check [List_of_Left_4_Dead_2_console_commands_and_variables](https://developer.valvesoftware.com/wiki/List_of_Left_4_Dead_2_console_commands_and_variables)
```
// Number of fragments for a splitpacket that can be sent per frame
net_splitrate 1
```

> 5. `+sv_lan 0` command line, can I remove it and instead put it in server.cfg as `sv_lan 0`?

Yes, you can

> 6. Duplicate value between server.cfg and server_rates.cfg: all items in `// Some tweaking` except `//sm_cvar z_brawl_chance 0`, can I remove `// Some tweaking` and its child in server_rates.cfg?

Update 8f504d8cb15ed4d42d493826d4f6de68bb1d3a7d

> Sorry for asking many question at once...

**Comment by deprid** [comment]
> Valve shit problem since update this year
Haha, such an annoying problem since it affects both server and clients

Thanks for the update, I've update new value for my server mirroring your new value, I put trust in you on this

**Comment by fbef0102** [comment]
> I notice missing `l4d2_resolve_collision_fix.ext.2.l4d2.so` in \extensions folder, so I add that one file from https://forums.alliedmods.net/showthread.php?t=344019

File is not missing
[Linux Server Files/left4dead2/addons/sourcemod/extensions/l4d2_resolve_collision_fix.ext.2.l4d2.so](https://github.com/fbef0102/L4D2-Server4Dead/blob/main/Linux%20Server%20Files/left4dead2/addons/sourcemod/extensions/l4d2_resolve_collision_fix.ext.2.l4d2.so)

**Comment by deprid** [comment]
> 1. Yesterday, I had 3 of my clients got kicked by the server. Never had this issue before. The message was: Kicked by Console : CBaseEntity::InputKill()). One of them managed to reconnect after got kicked. The map that we played was Crash Bandicoot. 3 of them happened in 3 different time/chapter. Question: is there something I need to change in server.cfg to prevent this from happening again? Or is this Valve problem?

There's apparently a fix for this issue already: [[L4D2] InputKill Kick Prevention - AlliedModders](https://forums.alliedmods.net/showthread.php?t=332860). But I've not tested this yet, will install the plugin when I have time.

![image](https://github.com/user-attachments/assets/1514c6d5-2630-4522-ae8a-c7c029882d33)

**Comment by fbef0102** [comment]
> There's apparently a fix for this issue already: [[L4D2] InputKill Kick Prevention - AlliedModders](https://forums.alliedmods.net/showthread.php?t=332860). But I've not tested this yet, will install the plugin when I have time.
> 
> ![image](https://private-user-images.githubusercontent.com/63422734/360732460-1514c6d5-2630-4522-ae8a-c7c029882d33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODMwOTYsIm5iZiI6MTcyNDM4Mjc5NiwicGF0aCI6Ii82MzQyMjczNC8zNjA3MzI0NjAtMTUxNGM2ZDUtMjYzMC00NTIyLWFlOGEtYzdjMDI5ODgyZDMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAzMTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNDRhZjYxZGFhOTQ1NTRiMmQ5MDkxNTczYTQyN2ZmMzc5ZjQ1Nzk3NWNmMjhkMTEzZmZkNzg5NDU5Y2NjM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LvXL_zq7fxQ7IB3-QVBbfVhhSu2DMyy1D6Ysm1ptyRg)

Good Work, know it now!
